apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secret
type: Opaque
data:
  DB_USER: ZGJhZG1pbg==
  DB_PASSWORD: TGVhcm5pbmdTZWN1cmVQYXNzd29yZDEyMyE=


# used command echo -n 'your-value' | base64 in gitbash to get encoded values for DS_USER and DB_PASSWORD
